workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean project
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Install pods
        script: cd ios && pod install && cd ..

      - name: Remove bad G flag
        script: |
          grep -R --line-number -- "-G" ios || true
          find ios -type f \( -name "*.xcconfig" -o -name "*.pbxproj" -o -name "*.sh" \) -exec sed -i '' 's/-G//g' {} \;
          grep -R --line-number -- "-G" ios || true

      - name: Build iOS
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
