// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQfrOEMkDEqKNsF3PlBK5C-W-w1Dgq7tw',
    appId: '1:386608552545:web:2244fe3b29bc56a4ec2820',
    messagingSenderId: '386608552545',
    projectId: 'birnefes-83398',
    authDomain: 'birnefes-83398.firebaseapp.com',
    databaseURL: 'https://birnefes-83398-default-rtdb.firebaseio.com',
    storageBucket: 'birnefes-83398.firebasestorage.app',
    measurementId: 'G-411EK6KQ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYPWEbJlArbRkSB-Q3-OX0F0HZbrvM6ck',
    appId: '1:386608552545:android:0cb0d52fbe916f79ec2820',
    messagingSenderId: '386608552545',
    projectId: 'birnefes-83398',
    databaseURL: 'https://birnefes-83398-default-rtdb.firebaseio.com',
    storageBucket: 'birnefes-83398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqwysy52wSSphJCPyo_3JuQZPZGLi-bY8',
    appId: '1:386608552545:ios:46c4c1162421d423ec2820',
    messagingSenderId: '386608552545',
    projectId: 'birnefes-83398',
    databaseURL: 'https://birnefes-83398-default-rtdb.firebaseio.com',
    storageBucket: 'birnefes-83398.firebasestorage.app',
    iosBundleId: 'com.ihtiyacim.ihtiyacim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqwysy52wSSphJCPyo_3JuQZPZGLi-bY8',
    appId: '1:386608552545:ios:46c4c1162421d423ec2820',
    messagingSenderId: '386608552545',
    projectId: 'birnefes-83398',
    databaseURL: 'https://birnefes-83398-default-rtdb.firebaseio.com',
    storageBucket: 'birnefes-83398.firebasestorage.app',
    iosBundleId: 'com.ihtiyacim.ihtiyacim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQfrOEMkDEqKNsF3PlBK5C-W-w1Dgq7tw',
    appId: '1:386608552545:web:cdce7735d0cb8513ec2820',
    messagingSenderId: '386608552545',
    projectId: 'birnefes-83398',
    authDomain: 'birnefes-83398.firebaseapp.com',
    databaseURL: 'https://birnefes-83398-default-rtdb.firebaseio.com',
    storageBucket: 'birnefes-83398.firebasestorage.app',
    measurementId: 'G-50174HG94T',
  );
}
