import 'quiz_question.dart';

class QuestionBank {
  static List<QuizQuestion> all() => const [
    // --- Başkent (TOPLAM 3) ---
    QuizQuestion(
      id: 'geo_001',
      category: 'Coğrafya',
      question: 'Hollanda’nın başkenti neresidir?',
      options: ['Amsterdam', 'Rotterdam', 'Utrecht', 'Eindhoven'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'geo_002',
      category: 'Coğrafya',
      question: 'Türkiye’nin başkenti neresidir?',
      options: ['İstanbul', 'Ankara', 'İzmir', 'Bursa'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'geo_003',
      category: 'Coğrafya',
      question: 'Fransa’nın başkenti neresidir?',
      options: ['Marsilya', 'Paris', 'Lyon', 'Nice'],
      correctIndex: 1,
    ),

    // --- Genel / Bilim / Tarih / Kültür / Mantık (Matematik yok) ---
    QuizQuestion(
      id: 'sci_001',
      category: 'Bilim',
      question: 'Su deniz seviyesinde kaç derecede kaynar?',
      options: ['90°C', '100°C', '110°C', '80°C'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'his_001',
      category: 'Tarih',
      question: 'Türkiye Cumhuriyeti hangi yıl kurulmuştur?',
      options: ['1919', '1920', '1923', '1938'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'gen_001',
      category: 'Genel',
      question: 'Dünyanın en büyük okyanusu hangisidir?',
      options: ['Atlas', 'Hint', 'Pasifik', 'Arktik'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'sci_002',
      category: 'Bilim',
      question: 'İnsan vücudundaki en büyük organ hangisidir?',
      options: ['Kalp', 'Akciğer', 'Deri', 'Karaciğer'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'gen_002',
      category: 'Genel',
      question: 'Haftada kaç gün vardır?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'tech_001',
      category: 'Teknoloji',
      question: 'Android uygulamaları çoğunlukla hangi dil ile yazılır?',
      options: ['Kotlin', 'Swift', 'Ruby', 'Go'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'sci_003',
      category: 'Bilim',
      question: 'Dünya Güneş’in etrafında yaklaşık kaç günde döner?',
      options: ['24', '180', '365', '730'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'geo_004',
      category: 'Coğrafya',
      question: 'En uzun nehir hangisidir?',
      options: ['Nil', 'Amazon', 'Fırat', 'Kızılırmak'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'gen_003',
      category: 'Genel',
      question: 'Kırmızı + Beyaz karışımı hangi renktir?',
      options: ['Pembe', 'Mor', 'Turuncu', 'Kahverengi'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'his_002',
      category: 'Tarih',
      question: 'İstanbul’un fethi hangi yıldır?',
      options: ['1453', '1520', '1071', '1918'],
      correctIndex: 0,
    ),

    // --- 1) Bilim ---
    QuizQuestion(
      id: 'sci_004',
      category: 'Bilim',
      question: 'Işığın boşluktaki hızı yaklaşık kaç km/sn’dir?',
      options: ['300.000', '30.000', '3.000', '1.500'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'sci_005',
      category: 'Bilim',
      question: 'DNA’nın açılımı aşağıdakilerden hangisine en yakındır?',
      options: ['Deoksiribonükleik asit', 'Dihidro nitrik asit', 'Dinamik nöral ağ', 'Dönüşümlü nükleer alan'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'sci_006',
      category: 'Bilim',
      question: 'İnsanlarda kanı pompalanan organ hangisidir?',
      options: ['Mide', 'Kalp', 'Böbrek', 'Karaciğer'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'sci_007',
      category: 'Bilim',
      question: 'Dünya’nın atmosferinde en çok bulunan gaz hangisidir?',
      options: ['Oksijen', 'Azot', 'Karbondioksit', 'Helyum'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'sci_008',
      category: 'Bilim',
      question: 'Gözümüzün renkli kısmının adı nedir?',
      options: ['İris', 'Retina', 'Kornea', 'Mercek'],
      correctIndex: 0,
    ),

    // --- 2) Tarih ---
    QuizQuestion(
      id: 'his_003',
      category: 'Tarih',
      question: 'Malazgirt Savaşı hangi yılda yapılmıştır?',
      options: ['1071', '1453', '1517', '1923'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'his_004',
      category: 'Tarih',
      question: 'Kurtuluş Savaşı’nda Batı Cephesi Komutanı olarak bilinen isim kimdir?',
      options: ['İsmet İnönü', 'Kazım Karabekir', 'Rauf Orbay', 'Fevzi Çakmak'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'his_005',
      category: 'Tarih',
      question: 'Roma İmparatorluğu’nun dili ağırlıklı olarak hangisiydi?',
      options: ['Latince', 'Arapça', 'Çince', 'İbranice'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'his_006',
      category: 'Tarih',
      question: 'Mısır’daki piramitler en çok hangi döneme aittir?',
      options: ['Antik Çağ', 'Orta Çağ', 'Yeni Çağ', 'Yakın Çağ'],
      correctIndex: 0,
    ),

    // --- 3) Coğrafya (başkent değil) ---
    QuizQuestion(
      id: 'geo_005',
      category: 'Coğrafya',
      question: 'Türkiye üç tarafı hangi tür su kütlesiyle çevrilidir?',
      options: ['Okyanus', 'Deniz', 'Göl', 'Nehir'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'geo_006',
      category: 'Coğrafya',
      question: 'Dünyanın en yüksek dağı hangisidir?',
      options: ['Everest', 'K2', 'Aconcagua', 'Elbruz'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'geo_007',
      category: 'Coğrafya',
      question: 'Sahra Çölü hangi kıtadadır?',
      options: ['Afrika', 'Asya', 'Avrupa', 'Güney Amerika'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'geo_008',
      category: 'Coğrafya',
      question: 'Ekvator çizgisi Dünya’yı hangi iki yarım küreye ayırır?',
      options: ['Doğu–Batı', 'Kuzey–Güney', 'Yukarı–Aşağı', 'Sağ–Sol'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'geo_009',
      category: 'Coğrafya',
      question: 'Karadeniz’i Akdeniz’e bağlayan su yolu aşağıdakilerden hangisidir?',
      options: ['Süveyş Kanalı', 'Panama Kanalı', 'İstanbul Boğazı ve Çanakkale Boğazı', 'Ren Nehri'],
      correctIndex: 2,
    ),

    // --- 4) Sanat / Edebiyat / Kültür ---
    QuizQuestion(
      id: 'art_001',
      category: 'Sanat',
      question: '“Mona Lisa” tablosunun ressamı kimdir?',
      options: ['Leonardo da Vinci', 'Van Gogh', 'Picasso', 'Michelangelo'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'art_002',
      category: 'Sanat',
      question: 'Tiyatroda sahne arkasında kullanılan “perde”yi yöneten kişiye ne denir?',
      options: ['Suflör', 'Rejisör', 'Dekoratör', 'Kondüktör'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'lit_001',
      category: 'Edebiyat',
      question: '“İnce Memed” romanının yazarı kimdir?',
      options: ['Yaşar Kemal', 'Orhan Pamuk', 'Sabahattin Ali', 'Aziz Nesin'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'lit_002',
      category: 'Edebiyat',
      question: 'Şiirde dizelerin bir araya gelmesiyle oluşan bölüme ne denir?',
      options: ['Kıta', 'Cümle', 'Paragraf', 'Başlık'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'cul_001',
      category: 'Kültür',
      question: '“Sushi” hangi ülke mutfağıyla özdeşleşmiştir?',
      options: ['Japonya', 'İtalya', 'Meksika', 'Hindistan'],
      correctIndex: 0,
    ),

    // --- 5) Spor ---
    QuizQuestion(
      id: 'sport_001',
      category: 'Spor',
      question: 'Futbolda bir takım sahada kaç oyuncuyla oynar?',
      options: ['9', '10', '11', '12'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'sport_002',
      category: 'Spor',
      question: 'Olimpiyat halkaları kaç tanedir?',
      options: ['4', '5', '6', '7'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'sport_003',
      category: 'Spor',
      question: 'Basketbolda sayı çizgisinin adı nedir?',
      options: ['Taç çizgisi', 'Üç sayı çizgisi', 'Orta çizgi', 'Kale çizgisi'],
      correctIndex: 1,
    ),

    // --- 6) Mantık / Dikkat (matematik değil) ---
    QuizQuestion(
      id: 'logic_001',
      category: 'Mantık',
      question: '“Tüm kediler hayvandır. Bazı hayvanlar siyahtır.” Buna göre hangisi kesin doğrudur?',
      options: ['Bazı kediler siyahtır', 'Kediler hayvandır', 'Tüm hayvanlar kedidir', 'Tüm kediler siyahtır'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'logic_002',
      category: 'Mantık',
      question: '“Dün bugünse yarın hangisi olur?” (Takvim oyunu)',
      options: ['Dün', 'Bugün', 'Yarın', 'Hiçbiri'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'logic_003',
      category: 'Mantık',
      question: 'Aşağıdakilerden hangisi diğerlerinden farklıdır?',
      options: ['Elma', 'Armut', 'Muz', 'Havuç'],
      correctIndex: 3,
    ),
    QuizQuestion(
      id: 'logic_004',
      category: 'Mantık',
      question: '“Kuşlar uçar. Penguen kuştur.” Buna göre hangisi çıkar?',
      options: ['Penguen uçar', 'Penguen kuş değildir', 'Genel kural istisna kaldırmaz', 'Verilenlerden kesin sonuç çıkmaz'],
      correctIndex: 3,
    ),
    QuizQuestion(
      id: 'logic_005',
      category: 'Mantık',
      question: '“Siyah değil” ifadesi aşağıdakilerden hangisine eşittir?',
      options: ['Beyaz', 'Renkli', 'Siyah olmayan', 'Gri'],
      correctIndex: 2,
    ),

    // --- 7) Teknoloji / İnternet ---
    QuizQuestion(
      id: 'tech_002',
      category: 'Teknoloji',
      question: 'Wi-Fi ne için kullanılır?',
      options: ['Kablosuz internet bağlantısı', 'Uydu yayını', 'Ses kaydı', 'Elektrik üretimi'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'tech_003',
      category: 'Teknoloji',
      question: '“URL” en çok neyi ifade eder?',
      options: ['Web adresi', 'Dosya adı', 'Şifre', 'Uygulama simgesi'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'tech_004',
      category: 'Teknoloji',
      question: 'Bilgisayarda “RAM” en çok neyle ilişkilidir?',
      options: ['Geçici bellek', 'Kalıcı depolama', 'Ekran kartı', 'İşletim sistemi'],
      correctIndex: 0,
    ),

    // --- 8) Genel bilgi çeşit ---
    QuizQuestion(
      id: 'gen_004',
      category: 'Genel',
      question: 'Dünyanın uydusu hangisidir?',
      options: ['Mars', 'Venüs', 'Ay', 'Güneş'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'gen_005',
      category: 'Genel',
      question: '“Kıta” nedir?',
      options: ['Büyük kara parçası', 'Küçük ada', 'Nehir yatağı', 'Deniz akıntısı'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'gen_006',
      category: 'Genel',
      question: '“Alfabede” Türkçede kaç harf vardır?',
      options: ['26', '28', '29', '30'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'gen_007',
      category: 'Genel',
      question: 'İnsanlarda kan grubunu belirleyen sistem aşağıdakilerden hangisidir?',
      options: ['ABO', 'ISO', 'GPS', 'CPU'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'gen_008',
      category: 'Genel',
      question: '“Termometre” ne ölçer?',
      options: ['Basınç', 'Sıcaklık', 'Hız', 'Mesafe'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'gen_009',
      category: 'Genel',
      question: 'Bir yılda kaç mevsim vardır?',
      options: ['2', '3', '4', '5'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'gen_010',
      category: 'Genel',
      question: 'Gökkuşağında hangi renk bulunmaz?',
      options: ['Mor', 'Siyah', 'Yeşil', 'Mavi'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'gen_011',
      category: 'Genel',
      question: 'Dünyanın şekli en doğru şekilde nasıl tanımlanır?',
      options: ['Küre', 'Düz', 'Üçgen', 'Kare'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'gen_012',
      category: 'Genel',
      question: '“SOS” sinyalinin amacı nedir?',
      options: ['Kutlama', 'Tehlike/yardım çağrısı', 'Selamlaşma', 'Hava durumu'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'gen_013',
      category: 'Genel',
      question: '“Buz” suyun hangi halidir?',
      options: ['Gaz', 'Sıvı', 'Katı', 'Plazma'],
      correctIndex: 2,
    ),
    QuizQuestion(
      id: 'gen_014',
      category: 'Genel',
      question: 'Türkiye’nin para birimi nedir?',
      options: ['Euro', 'Dolar', 'Türk Lirası', 'Sterlin'],
      correctIndex: 2,
    ),

    // --- 9) Daha fazla çeşit (rastgele tekrar azaltır) ---
    QuizQuestion(
      id: 'mix_001',
      category: 'Kültür',
      question: '“Kahve” bitkisi en çok hangi bölgede yetişmesiyle bilinir?',
      options: ['Tropikal kuşak', 'Kutuplar', 'Çöller', 'Tundra'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'mix_002',
      category: 'Bilim',
      question: 'Güneş bir “gezegen” midir?',
      options: ['Evet', 'Hayır, bir yıldızdır', 'Hayır, bir uydu', 'Hayır, bir asteroid'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'mix_003',
      category: 'Tarih',
      question: '“Rönesans” en çok hangi kıtada başlamıştır?',
      options: ['Avrupa', 'Asya', 'Afrika', 'Amerika'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'mix_004',
      category: 'Coğrafya',
      question: '“Kutupyıldızı” en çok hangi yönü bulmada kullanılır?',
      options: ['Kuzey', 'Güney', 'Doğu', 'Batı'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'mix_005',
      category: 'Teknoloji',
      question: '“Bluetooth” temel olarak ne işe yarar?',
      options: ['Kablosuz kısa mesafe bağlantı', 'Uydu iletişimi', 'Şarj etme', 'Ekran yansıtma zorunluluğu'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'mix_006',
      category: 'Mantık',
      question: 'Bir kelimenin tersi: “Az” kelimesinin zıttı nedir?',
      options: ['Çok', 'Kısa', 'Hızlı', 'Daha'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'mix_007',
      category: 'Genel',
      question: 'Bir üçgende iç açıların toplamı kaç derecedir?',
      options: ['90', '180', '270', '360'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'mix_008',
      category: 'Genel',
      question: '“Hakem” en çok hangi sporda kullanılır?',
      options: ['Sporların çoğunda', 'Sadece yüzmede', 'Sadece satrançta', 'Sadece okçulukta'],
      correctIndex: 0,
    ),
    QuizQuestion(
      id: 'mix_009',
      category: 'Bilim',
      question: 'Elektriği ileten maddelere ne denir?',
      options: ['Yalıtkan', 'İletken', 'Gaz', 'Çözücü'],
      correctIndex: 1,
    ),
    QuizQuestion(
      id: 'mix_010',
      category: 'Kültür',
      question: '“Dünya Sağlık Örgütü” kısaltması hangisidir?',
      options: ['WHO', 'UN', 'NATO', 'EU'],
      correctIndex: 0,
    ),
  ];
}