import '../game/quiz_question.dart';

class QuestionBank {
  static final List<QuizQuestion> questions = [
    QuizQuestion(
      id: 'q_0001',
      question: 'Dünyanın en derin noktası (okyanus) hangisidir?',
      options: ['Mariana Çukuru', 'Puerto Rico Çukuru', 'Java Çukuru', 'Tonga Çukuru'],
      correctIndex: 0,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0002',
      question: 'DNA’nın çift sarmal yapısını ilk kez doğru biçimde modelleyen ikili kimdir?',
      options: ['Watson & Crick', 'Newton & Leibniz', 'Curie & Curie', 'Bohr & Einstein'],
      correctIndex: 0,
      category: 'Bilim',
    ),
    QuizQuestion(
      id: 'q_0003',
      question: 'Roma rakamlarında “L” hangi sayıdır?',
      options: ['10', '50', '100', '500'],
      correctIndex: 1,
      category: 'Genel',
    ),
    QuizQuestion(
      id: 'q_0004',
      question: 'En küçük asal sayı hangisidir?',
      options: ['0', '1', '2', '3'],
      correctIndex: 2,
      category: 'Matematik',
    ),
    QuizQuestion(
      id: 'q_0005',
      question: '“Sefiller” romanının yazarı kimdir?',
      options: ['Victor Hugo', 'Lev Tolstoy', 'Charles Dickens', 'Albert Camus'],
      correctIndex: 0,
      category: 'Edebiyat',
    ),
    QuizQuestion(
      id: 'q_0006',
      question: 'İnsan vücudunda en fazla bulunan mineral hangisidir?',
      options: ['Demir', 'Kalsiyum', 'Magnezyum', 'Potasyum'],
      correctIndex: 1,
      category: 'Sağlık',
    ),
    QuizQuestion(
      id: 'q_0007',
      question: '“F=ma” hangi bilim insanıyla ilişkilidir?',
      options: ['Galileo', 'Newton', 'Tesla', 'Faraday'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0008',
      question: 'Dünya’nın atmosferinde en çok bulunan gaz hangisidir?',
      options: ['Oksijen', 'Azot', 'Karbondioksit', 'Argon'],
      correctIndex: 1,
      category: 'Bilim',
    ),
    QuizQuestion(
      id: 'q_0009',
      question: 'İstanbul Boğazı hangi iki denizi bağlar?',
      options: ['Ege - Marmara', 'Marmara - Karadeniz', 'Akdeniz - Ege', 'Karadeniz - Ege'],
      correctIndex: 1,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0010',
      question: 'Rönesans ilk olarak hangi ülkede başlamıştır?',
      options: ['Fransa', 'İtalya', 'İspanya', 'Almanya'],
      correctIndex: 1,
      category: 'Tarih',
    ),

    QuizQuestion(
      id: 'q_0011',
      question: 'Periyodik tabloda “Fe” hangi elementtir?',
      options: ['Flor', 'Demir', 'Fosfor', 'Fermiyum'],
      correctIndex: 1,
      category: 'Kimya',
    ),
    QuizQuestion(
      id: 'q_0012',
      question: 'Ay’a ilk ayak basan astronot kimdir?',
      options: ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Michael Collins'],
      correctIndex: 1,
      category: 'Uzay',
    ),
    QuizQuestion(
      id: 'q_0013',
      question: 'Bir üçgenin iç açılar toplamı kaç derecedir?',
      options: ['90', '120', '180', '360'],
      correctIndex: 2,
      category: 'Matematik',
    ),
    QuizQuestion(
      id: 'q_0014',
      question: '“Mona Lisa” tablosunun ressamı kimdir?',
      options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
      correctIndex: 1,
      category: 'Sanat',
    ),
    QuizQuestion(
      id: 'q_0015',
      question: 'Hangi organ insanda insülin üretir?',
      options: ['Karaciğer', 'Böbrek', 'Pankreas', 'Dalak'],
      correctIndex: 2,
      category: 'Sağlık',
    ),
    QuizQuestion(
      id: 'q_0016',
      question: '“HTTP” açılımı nedir?',
      options: [
        'HyperText Transfer Protocol',
        'HighText Transfer Program',
        'Hyper Transfer Text Process',
        'Host Transfer Text Protocol'
      ],
      correctIndex: 0,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0017',
      question: 'Dünyanın en büyük çölü hangisidir?',
      options: ['Sahra', 'Gobi', 'Antarktika', 'Kalahari'],
      correctIndex: 2,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0018',
      question: 'Dünya’nın kendi ekseni etrafında dönüş süresi yaklaşık kaç saattir?',
      options: ['12', '18', '24', '30'],
      correctIndex: 2,
      category: 'Genel',
    ),
    QuizQuestion(
      id: 'q_0019',
      question: 'Kıtaların kayması teorisi hangi bilim insanıyla ilişkilidir?',
      options: ['Darwin', 'Wegener', 'Pasteur', 'Kepler'],
      correctIndex: 1,
      category: 'Bilim',
    ),
    QuizQuestion(
      id: 'q_0020',
      question: 'Bir tam tur kaç radyandır?',
      options: ['π', '2π', 'π/2', '4π'],
      correctIndex: 1,
      category: 'Matematik',
    ),

    QuizQuestion(
      id: 'q_0021',
      question: 'Elektriği iletmede genellikle en iyi olan madde hangisidir?',
      options: ['Cam', 'Plastik', 'Bakır', 'Tahta'],
      correctIndex: 2,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0022',
      question: 'Türkiye’nin en uzun nehri hangisidir?',
      options: ['Kızılırmak', 'Fırat', 'Dicle', 'Sakarya'],
      correctIndex: 0,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0023',
      question: '“Mikro” ön eki neyi ifade eder?',
      options: ['10^-3', '10^-6', '10^-9', '10^3'],
      correctIndex: 1,
      category: 'Bilim',
    ),
    QuizQuestion(
      id: 'q_0024',
      question: 'İnsan vücudunda en büyük organ hangisidir?',
      options: ['Kalp', 'Karaciğer', 'Deri', 'Akciğer'],
      correctIndex: 2,
      category: 'Sağlık',
    ),
    QuizQuestion(
      id: 'q_0025',
      question: '“Kara delik” kavramı en çok hangi fizik alanıyla ilişkilidir?',
      options: ['Optik', 'Astrofizik', 'Akustik', 'Termodinamik'],
      correctIndex: 1,
      category: 'Uzay',
    ),
    QuizQuestion(
      id: 'q_0026',
      question: '“Buhar makinesi”nin sanayi devrimindeki gelişiminde adı öne çıkan kişi kimdir?',
      options: ['James Watt', 'Edison', 'Bell', 'Marconi'],
      correctIndex: 0,
      category: 'Tarih',
    ),
    QuizQuestion(
      id: 'q_0027',
      question: 'Bir bilgisayarda “RAM” ne için kullanılır?',
      options: ['Kalıcı depolama', 'Geçici bellek', 'Ekran kartı', 'İşlemci soğutma'],
      correctIndex: 1,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0028',
      question: '“Celsius” ölçeğinde suyun donma noktası kaçtır?',
      options: ['0', '32', '100', '-10'],
      correctIndex: 0,
      category: 'Bilim',
    ),
    QuizQuestion(
      id: 'q_0029',
      question: 'Türkiye’de “Kapadokya” hangi il ile en çok ilişkilidir?',
      options: ['Nevşehir', 'Muğla', 'Rize', 'Edirne'],
      correctIndex: 0,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0030',
      question: '“Fotosentez” en çok hangi organelde gerçekleşir?',
      options: ['Mitokondri', 'Ribozom', 'Kloroplast', 'Lizozom'],
      correctIndex: 2,
      category: 'Biyoloji',
    ),

    QuizQuestion(
      id: 'q_0031',
      question: 'Hangi gezegen “Kızıl Gezegen” olarak bilinir?',
      options: ['Mars', 'Jüpiter', 'Satürn', 'Uranüs'],
      correctIndex: 0,
      category: 'Uzay',
    ),
    QuizQuestion(
      id: 'q_0032',
      question: '“Habeas Corpus” ilkesi hangi ülke hukuk tarihinde önemlidir?',
      options: ['İngiltere', 'Japonya', 'Rusya', 'Brezilya'],
      correctIndex: 0,
      category: 'Tarih',
    ),
    QuizQuestion(
      id: 'q_0033',
      question: '“Tsunami” en çok hangi olay sonucu oluşur?',
      options: ['Kasırga', 'Deprem', 'Kuraklık', 'Heyelan'],
      correctIndex: 1,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0034',
      question: '“Atom numarası” neyi ifade eder?',
      options: ['Nötron sayısı', 'Proton sayısı', 'Elektron sayısı', 'Kütle numarası'],
      correctIndex: 1,
      category: 'Kimya',
    ),
    QuizQuestion(
      id: 'q_0035',
      question: 'Sıfırıncı derece meridyeni hangi yerden geçer?',
      options: ['Paris', 'Greenwich', 'Roma', 'Berlin'],
      correctIndex: 1,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0036',
      question: 'Kütle ve ağırlık arasındaki temel fark nedir?',
      options: ['Aynıdır', 'Kütle yerçekimine bağlıdır', 'Ağırlık yerçekimine bağlıdır', 'Ağırlık sabittir'],
      correctIndex: 2,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0037',
      question: 'Normal insan vücut sıcaklığı yaklaşık kaç °C’dir?',
      options: ['35', '36.5-37', '38.5', '40'],
      correctIndex: 1,
      category: 'Sağlık',
    ),
    QuizQuestion(
      id: 'q_0038',
      question: '“Süveyş Kanalı” hangi iki denizi bağlar?',
      options: ['Akdeniz - Kızıldeniz', 'Karadeniz - Marmara', 'Baltık - Kuzey', 'Ege - Akdeniz'],
      correctIndex: 0,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0039',
      question: '“Dijital imza” en çok hangi amaçla kullanılır?',
      options: ['Görüntü düzenleme', 'Kimlik doğrulama ve bütünlük', 'Oyun performansı', 'Ekran parlaklığı'],
      correctIndex: 1,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0040',
      question: '“Bir sayının kendisi ve 1 dışında böleni yoksa” bu sayı nedir?',
      options: ['Çift', 'Asal', 'Bileşik', 'Rasyonel'],
      correctIndex: 1,
      category: 'Matematik',
    ),

    QuizQuestion(
      id: 'q_0041',
      question: '“Kara kıta” olarak anılan kıta hangisidir?',
      options: ['Asya', 'Afrika', 'Avrupa', 'Güney Amerika'],
      correctIndex: 1,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0042',
      question: 'Elektronun yükü nasıl işaretlidir?',
      options: ['Pozitif', 'Negatif', 'Nötr', 'Değişken'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0043',
      question: '“Süpernova” nedir?',
      options: ['Yeni doğan yıldız', 'Yıldız patlaması', 'Gezegen çarpışması', 'Kuyruklu yıldız'],
      correctIndex: 1,
      category: 'Uzay',
    ),
    QuizQuestion(
      id: 'q_0044',
      question: '“E=mc²” denkleminde c neyi temsil eder?',
      options: ['Ses hızı', 'Işık hızı', 'Yerçekimi', 'Zaman'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0045',
      question: 'İnsan beyninde düşünme/karar verme ile en çok ilişkili bölge hangisidir?',
      options: ['Beyincik', 'Omurilik soğanı', 'Frontal lob', 'Talamus'],
      correctIndex: 2,
      category: 'Sağlık',
    ),
    QuizQuestion(
      id: 'q_0046',
      question: 'Bir dikdörtgenin alanı nasıl bulunur?',
      options: ['Kenar+kenar', 'Kenar×kenar', 'Uzunluk×genişlik', 'Çevre/2'],
      correctIndex: 2,
      category: 'Matematik',
    ),
    QuizQuestion(
      id: 'q_0047',
      question: '“WHO” kısaltması neyi ifade eder?',
      options: ['World Health Organization', 'World Help Office', 'Wide Health Order', 'World Human Output'],
      correctIndex: 0,
      category: 'Genel',
    ),
    QuizQuestion(
      id: 'q_0048',
      question: 'Bir bilgisayarda “CPU” neyi ifade eder?',
      options: ['Grafik birimi', 'Ana işlemci', 'Depolama', 'Ağ kartı'],
      correctIndex: 1,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0049',
      question: '“Sarkaç” hareketi en çok hangi kuvvetle ilişkilidir?',
      options: ['Manyetik', 'Yerçekimi', 'Sürtünme', 'Nükleer'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0050',
      question: 'Bir hexagon (altıgen) kaç kenarlıdır?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
      category: 'Matematik',
    ),

    // 50-100: daha zor/karışık karışık devam
    QuizQuestion(
      id: 'q_0051',
      question: '“Katalizör” ne yapar?',
      options: ['Tepkiyi durdurur', 'Tepki hızını artırır, tüketilmez', 'Suyu dondurur', 'Isıyı yok eder'],
      correctIndex: 1,
      category: 'Kimya',
    ),
    QuizQuestion(
      id: 'q_0052',
      question: 'Bakteriler hangi canlı grubuna girer?',
      options: ['Ökaryot', 'Prokaryot', 'Mantar', 'Bitki'],
      correctIndex: 1,
      category: 'Biyoloji',
    ),
    QuizQuestion(
      id: 'q_0053',
      question: 'Ağrı Dağı Türkiye’nin hangi bölgesindedir?',
      options: ['Ege', 'Doğu Anadolu', 'Marmara', 'Akdeniz'],
      correctIndex: 1,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0054',
      question: 'Güç birimi nedir?',
      options: ['Joule', 'Watt', 'Newton', 'Pascal'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0055',
      question: '.org uzantısı genelde neyi temsil eder?',
      options: ['Kişisel', 'Organizasyon', 'Devlet', 'Eğitim'],
      correctIndex: 1,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0056',
      question: '“Büyük Patlama” teorisi neyi açıklar?',
      options: ['Depremleri', 'Evrenin başlangıcını', 'Okyanus akıntılarını', 'Dünyanın iç yapısını'],
      correctIndex: 1,
      category: 'Uzay',
    ),
    QuizQuestion(
      id: 'q_0057',
      question: 'Hücre zarının temel görevi nedir?',
      options: ['Protein üretmek', 'Madde alışverişini kontrol etmek', 'Enerji üretmek', 'DNA’yı çoğaltmak'],
      correctIndex: 1,
      category: 'Biyoloji',
    ),
    QuizQuestion(
      id: 'q_0058',
      question: 'Aritmetik ortalama nasıl bulunur?',
      options: ['Çarpma', 'Toplam / adet', 'Bölme', 'Çıkarma'],
      correctIndex: 1,
      category: 'Matematik',
    ),
    QuizQuestion(
      id: 'q_0059',
      question: 'Karbondioksitin formülü nedir?',
      options: ['CO', 'CO2', 'C2O', 'O2C'],
      correctIndex: 1,
      category: 'Kimya',
    ),
    QuizQuestion(
      id: 'q_0060',
      question: 'Ampere hangi büyüklüğün birimidir?',
      options: ['Gerilim', 'Akım', 'Direnç', 'Güç'],
      correctIndex: 1,
      category: 'Fizik',
    ),

    QuizQuestion(
      id: 'q_0061',
      question: 'Helsinki hangi ülkenin başkentidir?',
      options: ['Norveç', 'Finlandiya', 'İsveç', 'Danimarka'],
      correctIndex: 1,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0062',
      question: 'Süblimleşme nedir?',
      options: ['Sıvıdan gaza', 'Katıdan gaza', 'Gazdan sıvıya', 'Sıvıdan katıya'],
      correctIndex: 1,
      category: 'Kimya',
    ),
    QuizQuestion(
      id: 'q_0063',
      question: 'ASCII neyle ilgilidir?',
      options: ['Şifreleme algoritması', 'Metin karakter kodlaması', 'Resim sıkıştırma', 'Ağ protokolü'],
      correctIndex: 1,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0064',
      question: 'Büyüteç hangi optik elemandır?',
      options: ['Çukur ayna', 'İnce kenarlı mercek', 'Kalın kenarlı mercek', 'Düz ayna'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0065',
      question: 'Bir litrede kaç mililitre vardır?',
      options: ['10', '100', '1000', '10000'],
      correctIndex: 2,
      category: 'Genel',
    ),
    QuizQuestion(
      id: 'q_0066',
      question: 'Pi sayısının yaklaşık değeri hangisidir?',
      options: ['2.14', '3.14', '4.13', '1.34'],
      correctIndex: 1,
      category: 'Matematik',
    ),
    QuizQuestion(
      id: 'q_0067',
      question: 'Böbreklerin temel görevi nedir?',
      options: ['Oksijen taşımak', 'Atıkları süzmek', 'İnsülin üretmek', 'Safra üretmek'],
      correctIndex: 1,
      category: 'Sağlık',
    ),
    QuizQuestion(
      id: 'q_0068',
      question: 'Beyaz ışık prizmadan geçince ne olur?',
      options: ['Tek renge dönüşür', 'Renklerine ayrılır', 'Yok olur', 'Siyaha döner'],
      correctIndex: 1,
      category: 'Fizik',
    ),
    QuizQuestion(
      id: 'q_0069',
      question: 'Ekvator hangi enlem derecesidir?',
      options: ['0°', '30°', '45°', '90°'],
      correctIndex: 0,
      category: 'Coğrafya',
    ),
    QuizQuestion(
      id: 'q_0070',
      question: 'Oksidasyon genel olarak neyi ifade eder?',
      options: ['Elektron almak', 'Elektron vermek', 'Asitlik azalması', 'Basınç artması'],
      correctIndex: 1,
      category: 'Kimya',
    ),

    QuizQuestion(
      id: 'q_0071',
      question: 'Mitoz bölünmenin sonucu genelde nedir?',
      options: ['2 aynı hücre', '4 farklı hücre', '1 hücre', 'Sonsuz hücre'],
      correctIndex: 0,
      category: 'Biyoloji',
    ),
    QuizQuestion(
      id: 'q_0072',
      question: 'Bir byte kaç bittir?',
      options: ['4', '8', '16', '32'],
      correctIndex: 1,
      category: 'Teknoloji',
    ),
    QuizQuestion(
      id: 'q_0073',
      question: 'Dünya’da yerçekimi ivmesi (g) yaklaşık kaçtır?',
      options: ['1.6', '3.7', '9.8', '24.8'],
      correctIndex: 2,
      category: 'Fizik',
    ),

    // Kalanları hızlı tamamlayalım (74-100)
    QuizQuestion(id: 'q_0074', question: 'İnsan kanında oksijeni en çok taşıyan yapı hangisidir?', options: ['Akyuvar', 'Hemoglobin', 'Trombosit', 'Plazma'], correctIndex: 1, category: 'Sağlık'),
    QuizQuestion(id: 'q_0075', question: '“D vitamini” vücutta en çok nasıl sentezlenir?', options: ['Yemekle', 'Güneş ışığıyla', 'Uyurken', 'Su içerek'], correctIndex: 1, category: 'Sağlık'),
    QuizQuestion(id: 'q_0076', question: '“Kuantum” kelimesi en çok hangi alanda geçer?', options: ['Klasik mekanik', 'Kuantum mekaniği', 'Statik', 'Akışkanlar'], correctIndex: 1, category: 'Fizik'),
    QuizQuestion(id: 'q_0077', question: 'Balkanlar hangi kıtadadır?', options: ['Asya', 'Avrupa', 'Afrika', 'Okyanusya'], correctIndex: 1, category: 'Coğrafya'),
    QuizQuestion(id: 'q_0078', question: 'Suyun kaynama noktası (deniz seviyesinde) kaç °C’dir?', options: ['90', '95', '100', '110'], correctIndex: 2, category: 'Bilim'),
    QuizQuestion(id: 'q_0079', question: '“NaCl” hangi bileşiktir?', options: ['Şeker', 'Tuz', 'Karbonat', 'Amonyak'], correctIndex: 1, category: 'Kimya'),
    QuizQuestion(id: 'q_0080', question: 'Dünyanın en büyük okyanusu hangisidir?', options: ['Atlas', 'Hint', 'Pasifik', 'Arktik'], correctIndex: 2, category: 'Coğrafya'),
    QuizQuestion(id: 'q_0081', question: 'Bir küpün kaç yüzü vardır?', options: ['4', '6', '8', '12'], correctIndex: 1, category: 'Matematik'),
    QuizQuestion(id: 'q_0082', question: 'En büyük gezegen hangisidir?', options: ['Mars', 'Jüpiter', 'Venüs', 'Merkür'], correctIndex: 1, category: 'Uzay'),
    QuizQuestion(id: 'q_0083', question: '“Nöron” nedir?', options: ['Kas hücresi', 'Sinir hücresi', 'Kan hücresi', 'Kemik hücresi'], correctIndex: 1, category: 'Biyoloji'),
    QuizQuestion(id: 'q_0084', question: '“İnternet”in temel çalışma mantığı hangi yapıya dayanır?', options: ['Tek merkez', 'Dağıtık ağ', 'Analog yayın', 'Radyo dalgası'], correctIndex: 1, category: 'Teknoloji'),
    QuizQuestion(id: 'q_0085', question: '“Euler sayısı” yaklaşık kaçtır?', options: ['1.41', '2.71', '3.14', '0.57'], correctIndex: 1, category: 'Matematik'),
    QuizQuestion(id: 'q_0086', question: '“Sürtünme kuvveti” genelde neye zıt yöndedir?', options: ['Hareket', 'Ağırlık', 'Manyetik', 'Basınç'], correctIndex: 0, category: 'Fizik'),
    QuizQuestion(id: 'q_0087', question: '“Teleskop” en çok neyi gözlemlemek için kullanılır?', options: ['Mikrop', 'Yıldız/gezegen', 'DNA', 'Atom'], correctIndex: 1, category: 'Uzay'),
    QuizQuestion(id: 'q_0088', question: 'Bir sayının 0 ile çarpımı kaçtır?', options: ['0', '1', 'Sayı', 'Bilinmez'], correctIndex: 0, category: 'Matematik'),
    QuizQuestion(id: 'q_0089', question: '“Hidrolik” sistemler en çok hangi prensiple çalışır?', options: ['Pascal', 'Newton', 'Ohm', 'Avogadro'], correctIndex: 0, category: 'Fizik'),
    QuizQuestion(id: 'q_0090', question: 'İnsanlarda kan grubunu belirleyen sistem en yaygın hangisidir?', options: ['ABO', 'XYZ', 'LMN', 'RST'], correctIndex: 0, category: 'Sağlık'),
    QuizQuestion(id: 'q_0091', question: '“Ozon tabakası” en çok hangi tür ışınımı engeller?', options: ['Kızılötesi', 'UV', 'Radyo', 'Ses'], correctIndex: 1, category: 'Bilim'),
    QuizQuestion(id: 'q_0092', question: '“Bit” ve “Byte” ilişkisi hangisidir?', options: ['1 Byte=2 bit', '1 Byte=4 bit', '1 Byte=8 bit', '1 Byte=16 bit'], correctIndex: 2, category: 'Teknoloji'),
    QuizQuestion(id: 'q_0093', question: '“pH” neyi ölçer?', options: ['Sıcaklık', 'Asitlik-bazlık', 'Basınç', 'Hız'], correctIndex: 1, category: 'Kimya'),
    QuizQuestion(id: 'q_0094', question: '“İzotop” ne demektir?', options: ['Aynı proton farklı nötron', 'Aynı nötron farklı proton', 'Aynı elektron farklı proton', 'Aynı kütle farklı atom'], correctIndex: 0, category: 'Kimya'),
    QuizQuestion(id: 'q_0095', question: 'Dünya’nın uydusu nedir?', options: ['Güneş', 'Ay', 'Mars', 'Venüs'], correctIndex: 1, category: 'Uzay'),
    QuizQuestion(id: 'q_0096', question: '“Algoritma” ne demektir?', options: ['Rastgele işlem', 'Adım adım çözüm yöntemi', 'Sadece formül', 'Sadece kod'], correctIndex: 1, category: 'Teknoloji'),
    QuizQuestion(id: 'q_0097', question: '“Güneş sistemi” hangi galaksidedir?', options: ['Andromeda', 'Samanyolu', 'Sombrero', 'Triangulum'], correctIndex: 1, category: 'Uzay'),
    QuizQuestion(id: 'q_0098', question: '“Termometre” neyi ölçer?', options: ['Nem', 'Sıcaklık', 'Basınç', 'Işık'], correctIndex: 1, category: 'Bilim'),
    QuizQuestion(id: 'q_0099', question: 'Bir dairenin çevresi formülü hangisidir?', options: ['πr²', '2πr', 'r²', 'π/2'], correctIndex: 1, category: 'Matematik'),
    QuizQuestion(id: 'q_0100', question: '“Klorofil” ne işe yarar?', options: ['Solunum', 'Fotosentezde ışığı soğurur', 'Sindirim', 'Hareket'], correctIndex: 1, category: 'Biyoloji'),
  ];
}